channels:
  - conda-forge
dependencies:
  - python=3.11.13
  - pip<=25.1
  - pip:
      - mlflow==2.19.0
      - cloudpickle==3.0.0
      - pandas==2.2.3
      - psutil==5.9.4
      - scikit-learn==1.6.1
      - xgboost==3.0.1
name: mlflow-env
